<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>net5</TargetFrameworks>
	  <Version>1.0.1</Version>
	  <Description>
		  基于MailKit的跨平台.NET邮件库，支持IMAP、POP3、SMTP协议
		  github:https://github.com/jstedfast/MailKit
	  </Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Sms\**" />
    <EmbeddedResource Remove="Sms\**" />
    <None Remove="Sms\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="3.2.0" />
  </ItemGroup>
</Project>