<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net5</TargetFramework>
	  <Version>1.0.2-rc4.8.5</Version>
	  <Description>
		  模块共享类库
	  </Description>
    <AssemblyName>MF.Modules.UserCenter.Shared</AssemblyName>
    <RootNamespace>MF.Modules.UserCenter.Shared</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MF\MF.FluentValidation\MF.FluentValidation.csproj" />
    <ProjectReference Include="..\..\MF\MF.Orm\MF.Orm.csproj" />
  </ItemGroup>
</Project>