<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net5.0</TargetFramework>
	  <Version>1.0.3-rc7</Version>
	  <Description>
      +修复 异常中间件已知问题
      +新增 导出EXCELsheet名参数传入指定,默认sheet
    </Description>
	  <PackageReleaseNotes>
      +修复 异常中间件 -add by caladi 2022/2/23
      +新增 导出EXCELsheet名参数传入指定,默认sheet --add by corbin 2022/3/30
    </PackageReleaseNotes>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="4.1.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.0" />
    <PackageReference Include="Microsoft.QualityTools.Testing.Fakes" Version="16.7.4-beta.20330.2" />
    <PackageReference Include="Microsoft.Win32.Registry" Version="6.0.0-preview.5.21301.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MF.FluentValidation\MF.FluentValidation.csproj" />
    <ProjectReference Include="..\MF.Rest\MF.Rest.csproj" />
    <ProjectReference Include="..\MF.Swagger\MF.Swagger.csproj" />
    <ProjectReference Include="..\MF.Utils.Excel\MF.Utils.Excel.csproj" />
    <ProjectReference Include="..\MF.Utils\MF.Utils.csproj" />
  </ItemGroup>
</Project>