<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>net5</TargetFrameworks>
	  <Version>1.0.3-rc6</Version>
	  <Description>
		 Excel任务导出
	  </Description>
	  <PackageReleaseNotes>
		  +更新MF.Job.Core引用
		  +修复 Job任务导出数据错误-2022/3/24
		  +修复 Job任务导出Token失效问题-2022/4/27
	  </PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Quartz" Version="3.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MF.Job.Core\MF.Job.Core.csproj" />
    <ProjectReference Include="..\MF.Log\MF.Log.csproj" />
    <ProjectReference Include="..\MF.Rest\MF.Rest.csproj" />
  </ItemGroup>

</Project>
