<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>net5</TargetFrameworks>
	  <Version>1.0.4-rc4.2</Version>
	  <Description>
		 Excel任务导出
	  </Description>
	  <PackageReleaseNotes>
		  +更新MF.Job.Core引用
		  +修复 Job任务导出数据错误-2022/3/24
		  +修复 Job任务导出Token失效问题-2022/4/27
		  +修复 修改获取token方式(目前写死sysytem密码为123456 后期修改密码后将无法进行导出)-2022/7/21
		  +修复 定期删除Job任务无法执行问题-2022/8/5
		  +优化 结束时间可空 -2022/8/5
	  </PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Quartz" Version="3.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MF.Job.Core\MF.Job.Core.csproj" />
    <ProjectReference Include="..\MF.Log\MF.Log.csproj" />
    <ProjectReference Include="..\MF.Rest\MF.Rest.csproj" />
  </ItemGroup>

</Project>
