<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net5</TargetFramework>
	  <Version>1.0.1-rc7.5</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MF.MediatR\MF.MediatR.csproj" />
    <ProjectReference Include="..\MF.Utils\MF.Utils.csproj" />
  </ItemGroup>
</Project>