<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>net5</TargetFrameworks>
    <RootNamespace>MF.ApiJob</RootNamespace>
    <AssemblyName>MF.ApiJob</AssemblyName>
	  <Version>1.0.5-rc7.3.7</Version>
	  <Description>
		  +优化调用apijob时get类型请求,参数异常问题
	  </Description>
	  <PackageReleaseNotes>
      +优化 第三方自定义接口token问题-2022/8/10
      +更新MF.Job.Core引用
      +优化调用apijob时get类型请求,参数异常问题
    </PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Quartz" Version="3.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MF.Job.Core\MF.Job.Core.csproj" />
    <ProjectReference Include="..\MF.Log\MF.Log.csproj" />
    <ProjectReference Include="..\MF.Rest\MF.Rest.csproj" />
  </ItemGroup>
</Project>