<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net5.0</TargetFrameworks> 
	  <Version>1.0.1-rc4.8</Version>
	  <Description>
      +修复 导出EXCEL字体颜色、加粗
      +新增 导出EXCELsheet名参数传入指定,默认sheet
      +修复 导入EXCEL存在空行bug
    </Description>
	  <PackageReleaseNotes>
		  +修复 导出EXCEL字体颜色、加粗 -add by caladi 2022/2/8
		  +新增 导出EXCELsheet名参数传入指定,默认sheet  --add by corbin 2022/3/30
		  +修复 导入EXCEL存在空行bug  --add by corbin 2022/3/31
		  +新增 报表平台导出接口  --add by caladi 2022/5/20
		  +新增 设备点检导出接口  --add by caladi 2022/8/24
	  </PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetCore.NPOI" Version="1.2.3" />
    <PackageReference Include="EPPlus" Version="6.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
    <PackageReference Include="MiniExcel" Version="1.26.2" />
  </ItemGroup>
</Project>