<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
     <TargetFramework>net5</TargetFramework> 
	  <Version>1.0.1-rc1</Version>
	  <Description>
		  +修复 导出EXCEL字体颜色、加粗
	  </Description>
	  <PackageReleaseNotes>
		  +修复 导出EXCEL字体颜色、加粗 -add by caladi 2022/2/8
	  </PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetCore.NPOI" Version="1.2.3" />
    <PackageReference Include="EPPlus" Version="5.4.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
    <PackageReference Include="MiniExcel" Version="0.19.1" />
  </ItemGroup>
</Project>