<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net5.0</TargetFrameworks>
	  <Version>1.0.1</Version>
    <RootNamespace>MF.Consul</RootNamespace>
    <AssemblyName>MF.Consul</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Consul" Version="1.6.10.5" />
  </ItemGroup>
</Project>