<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net5.0</TargetFrameworks>
	  <Version>1.0.1.4</Version>
	  <Description>代码生成器</Description>
	  <PackageReleaseNotes>
		  代码生成器
	  </PackageReleaseNotes>
	  <AssemblyName>MF.CodeGen</AssemblyName>
	  <RootNamespace>MF.CodeGen</RootNamespace>
	  <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
	  <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MF.Authorization\MF.Authorization.csproj" />
  </ItemGroup>

</Project>
