<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net5</TargetFramework>
	  <Version>1.0.2</Version>
	  <Description>
		  +修复 调度任务界面无法带参查询
	  </Description>
	  <PackageReleaseNotes>
		  1.修复 任务调度界面无法带参查询-2022/3/2
	  </PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SqlSugarCore" Version="5.0.7.7-preview03" />
  </ItemGroup>

</Project>
