<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net5</TargetFramework>
	  <Version>1.0.4-rc5.1.1</Version>
	  <Description>
		  +修复 调度任务界面无法带参查询
	  </Description>
	  <PackageReleaseNotes>
		  1.修复 任务调度界面无法带参查询-2022/3/2
		  2.修复 任务名称不可重复添加以及关键的参数不允许为空-2022/10/27
	  </PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SqlSugarCore" Version="5.1.3.29" />
  </ItemGroup>

</Project>
