<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>net5</TargetFrameworks>
    <Platforms>AnyCPU;ARM64</Platforms>
    <Version>1.0.2</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MF.Orm" Version="1.0.3" />
    <PackageReference Include="MQTTnet" Version="3.1.1" />
    <PackageReference Include="StackExchange.Redis" Version="2.2.88" />
  </ItemGroup>

</Project>
