<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>net5</TargetFrameworks>
    <Platforms>AnyCPU;ARM64</Platforms>
    <Version>1.0.3-rc9</Version>
    <PackageReleaseNotes>优化mqttclient，并进行异常测试:(1)断服务器(2)超时</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MQTTnet" Version="3.1.1" />
    <PackageReference Include="StackExchange.Redis" Version="2.2.88" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MF.Orm\MF.Orm.csproj" />
  </ItemGroup>

</Project>
