<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net5.0</TargetFrameworks>
    <Platforms>AnyCPU;ARM64</Platforms>
    <Version>1.1.0</Version>
    <Description>修复自定义流水号按年不加1的bug;新增自定义流水号按最大值重置</Description>
    <PackageReleaseNotes>
      1、机器码记录到日志
      2、优化日志组件
      3、优化日志组件、资源锁实现
      4、优化DB连接池
      5、优化日志组件
      6、新增redis连接状态变量,更新MQTTnet(3.1.1=&gt;3.1.2)
      7、优化SqlSugarScope的日志事件
      8、QualityDataType对象新增BitType字段
      9、SqlSugarScope新增属性:将nvarchar参数全部转成varchar模式
      10、优化日志路径赋值
      11、mqttClient初始化日志记录
      12、修复自定义流水号按年不加1的bug;新增自定义流水号按最大值重置
    </PackageReleaseNotes>
    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MQTTnet" Version="3.1.2" />
    <PackageReference Include="StackExchange.Redis" Version="2.2.88" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MF.Orm\MF.Orm.csproj" />
  </ItemGroup>

</Project>
