<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>netcoreapp3.1;net5</TargetFrameworks>
    <Version>1.0.1-rc2</Version>
    <Description>
      +优化算法
    </Description>
    <PackageReleaseNotes>
      +优化算法-2023/8/28
      +优化算法-2023/12/21
    </PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="7.0.2" />
    <PackageReference Include="System.Drawing.Common" Version="5.0.2" />
  </ItemGroup>

</Project>
