using System;
using System.Data;
using System.IO;
using System.Runtime.Serialization;

namespace MF.Utils.SPC
{
    /// <summary>
    /// XmlSchemaDataSet 的摘要说明。
    /// 用XML构架文件创建符合绘制图表的DataSet表结构
    /// 表名称：ChartParameter 字段名称前面进行了定义。（使用这种方法的好处是脱离数据库，多用户同时读取并保证速度）
    /// </summary>
    [System.ComponentModel.DesignerCategory("Code")]
    [Serializable]
    public class Xml_Spc_Param : DataSet
    {
        public const string Table_Name = "ChartParameter";
        public const string Param_ID = "ID";
        public const string Param_NUM = "NUM";
        public const string Param_A = "A";
        public const string Param_A2 = "A2";
        public const string Param_A3 = "A3";
        public const string Param_B3 = "B3";
        public const string Param_B4 = "B4";
        public const string Param_B5 = "B5";
        public const string Param_B6 = "B6";
        public const string Param_D1 = "D1";
        public const string Param_D2 = "D2";
        public const string Param_D3 = "D3";
        public const string Param_D4 = "D4";
        public const string Param_C4 = "C4";
        public const string Param_C4_1 = "C4_1";
        public const string Param_L_D1 = "L_D1";
        public const string Param_L_D1_1 = "L_D1_1";

        /// <summary>
        ///     Constructor to support serialization.
        ///     <remarks>Constructor that supports serialization.</remarks>
        ///     <param name="info">The SerializationInfo object to read from.</param>
        ///     <param name="context">Information on who is calling this method.</param>
        /// </summary>
        private Xml_Spc_Param(SerializationInfo info, StreamingContext context) : base(info, context)
        {
        }

        /// <summary>
        /// 用XML构架文件创建符合绘制图表的DataSet表结构
        /// 表名称：ChartParameter			字段名称
        /// </summary>
        public Xml_Spc_Param()
        {
            this.ReadXml(InitchartDataXSD());
        }

        /// <summary>
        /// xml构架文件文本，用来创建绘制图表数据XML数据的基本框架。
        /// </summary>
        /// <returns></returns>
        private StringReader InitchartDataXSD()
        {
            StringReader stream;

            string chartDataXSD;

            chartDataXSD = "<?xml version=\"1.0\" standalone=\"yes\"?>";
            chartDataXSD += "<NewDataSet>";
            chartDataXSD += "<xs:schema id=\"NewDataSet\" xmlns=\"\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" xmlns:msdata=\"urn:schemas-microsoft-com:xml-msdata\">";
            chartDataXSD += "<xs:element name=\"NewDataSet\" msdata:IsDataSet=\"true\" msdata:Locale=\"zh-CN\">";
            chartDataXSD += "<xs:complexType>";
            chartDataXSD += "<xs:choice maxOccurs=\"unbounded\">";
            chartDataXSD += "<xs:element name=\"ChartParameter\">";
            chartDataXSD += "<xs:complexType>";
            chartDataXSD += "<xs:sequence>";
            chartDataXSD += "<xs:element name=\"ID\" type=\"xs:int\" minOccurs=\"0\" />";
            chartDataXSD += "<xs:element name=\"NUM\" type=\"xs:int\" minOccurs=\"0\" />";
            chartDataXSD += "<xs:element name=\"A\" type=\"xs:double\" minOccurs=\"0\" />";
            chartDataXSD += "<xs:element name=\"A2\" type=\"xs:double\" minOccurs=\"0\" />";
            chartDataXSD += "<xs:element name=\"A3\" type=\"xs:double\" minOccurs=\"0\" />";
            chartDataXSD += "<xs:element name=\"B3\" type=\"xs:double\" minOccurs=\"0\" />";
            chartDataXSD += "<xs:element name=\"B4\" type=\"xs:double\" minOccurs=\"0\" />";
            chartDataXSD += "<xs:element name=\"B5\" type=\"xs:double\" minOccurs=\"0\" />";
            chartDataXSD += "<xs:element name=\"B6\" type=\"xs:double\" minOccurs=\"0\" />";
            chartDataXSD += "<xs:element name=\"D1\" type=\"xs:double\" minOccurs=\"0\" />";
            chartDataXSD += "<xs:element name=\"D2\" type=\"xs:double\" minOccurs=\"0\" />";
            chartDataXSD += "<xs:element name=\"D3\" type=\"xs:double\" minOccurs=\"0\" />";
            chartDataXSD += "<xs:element name=\"D4\" type=\"xs:double\" minOccurs=\"0\" />";
            chartDataXSD += "<xs:element name=\"C4\" type=\"xs:double\" minOccurs=\"0\" />";
            chartDataXSD += "<xs:element name=\"C4_1\" type=\"xs:double\" minOccurs=\"0\" />";
            chartDataXSD += "<xs:element name=\"L_D1\" type=\"xs:double\" minOccurs=\"0\" />";
            chartDataXSD += "<xs:element name=\"L_D1_1\" type=\"xs:double\" minOccurs=\"0\" />";
            chartDataXSD += "</xs:sequence>";
            chartDataXSD += "</xs:complexType>";
            chartDataXSD += "</xs:element>";
            chartDataXSD += "</xs:choice>";
            chartDataXSD += "</xs:complexType>";
            chartDataXSD += "</xs:element>";
            chartDataXSD += "</xs:schema>";
            chartDataXSD += "<ChartParameter>";
            chartDataXSD += "<ID>1</ID>";
            chartDataXSD += "<NUM>2</NUM>";
            chartDataXSD += "<A>2.121</A>";
            chartDataXSD += "<A2>1.88</A2>";
            chartDataXSD += "<A3>2.659</A3>";
            chartDataXSD += "<B3>0</B3>";
            chartDataXSD += "<B4>3.267</B4>";
            chartDataXSD += "<B5>0</B5>";
            chartDataXSD += "<B6>2.606</B6>";
            chartDataXSD += "<D1>0</D1>";
            chartDataXSD += "<D2>3.686</D2>";
            chartDataXSD += "<D3>0</D3>";
            chartDataXSD += "<D4>3.267</D4>";
            chartDataXSD += "<C4>0.7979</C4>";
            chartDataXSD += "<C4_1>1.2533</C4_1>";
            chartDataXSD += "<L_D1>1.128</L_D1>";
            chartDataXSD += "<L_D1_1>0.8865</L_D1_1>";
            chartDataXSD += "</ChartParameter>";
            chartDataXSD += "<ChartParameter>";
            chartDataXSD += "<ID>2</ID>";
            chartDataXSD += "<NUM>3</NUM>";
            chartDataXSD += "<A>1.732</A>";
            chartDataXSD += "<A2>1.023</A2>";
            chartDataXSD += "<A3>1.954</A3>";
            chartDataXSD += "<B3>0</B3>";
            chartDataXSD += "<B4>2.568</B4>";
            chartDataXSD += "<B5>0</B5>";
            chartDataXSD += "<B6>2.676</B6>";
            chartDataXSD += "<D1>0</D1>";
            chartDataXSD += "<D2>4.358</D2>";
            chartDataXSD += "<D3>0</D3>";
            chartDataXSD += "<D4>2.574</D4>";
            chartDataXSD += "<C4>0.8862</C4>";
            chartDataXSD += "<C4_1>1.1284</C4_1>";
            chartDataXSD += "<L_D1>1.693</L_D1>";
            chartDataXSD += "<L_D1_1>0.5907</L_D1_1>";
            chartDataXSD += "</ChartParameter>";
            chartDataXSD += "<ChartParameter>";
            chartDataXSD += "<ID>3</ID>";
            chartDataXSD += "<NUM>4</NUM>";
            chartDataXSD += "<A>1.5</A>";
            chartDataXSD += "<A2>0.729</A2>";
            chartDataXSD += "<A3>1.628</A3>";
            chartDataXSD += "<B3>0</B3>";
            chartDataXSD += "<B4>2.266</B4>";
            chartDataXSD += "<B5>0</B5>";
            chartDataXSD += "<B6>2.088</B6>";
            chartDataXSD += "<D1>0</D1>";
            chartDataXSD += "<D2>4.698</D2>";
            chartDataXSD += "<D3>0</D3>";
            chartDataXSD += "<D4>2.282</D4>";
            chartDataXSD += "<C4>0.9213</C4>";
            chartDataXSD += "<C4_1>1.0854</C4_1>";
            chartDataXSD += "<L_D1>2.059</L_D1>";
            chartDataXSD += "<L_D1_1>0.4857</L_D1_1>";
            chartDataXSD += "</ChartParameter>";
            chartDataXSD += "<ChartParameter>";
            chartDataXSD += "<ID>4</ID>";
            chartDataXSD += "<NUM>5</NUM>";
            chartDataXSD += "<A>1.342</A>";
            chartDataXSD += "<A2>0.577</A2>";
            chartDataXSD += "<A3>1.427</A3>";
            chartDataXSD += "<B3>0</B3>";
            chartDataXSD += "<B4>2.089</B4>";
            chartDataXSD += "<B5>0</B5>";
            chartDataXSD += "<B6>1.964</B6>";
            chartDataXSD += "<D1>0</D1>";
            chartDataXSD += "<D2>4.918</D2>";
            chartDataXSD += "<D3>0</D3>";
            chartDataXSD += "<D4>2.114</D4>";
            chartDataXSD += "<C4>0.94</C4>";
            chartDataXSD += "<C4_1>1.0638</C4_1>";
            chartDataXSD += "<L_D1>2.326</L_D1>";
            chartDataXSD += "<L_D1_1>0.4299</L_D1_1>";
            chartDataXSD += "</ChartParameter>";
            chartDataXSD += "<ChartParameter>";
            chartDataXSD += "<ID>5</ID>";
            chartDataXSD += "<NUM>6</NUM>";
            chartDataXSD += "<A>1.225</A>";
            chartDataXSD += "<A2>0.483</A2>";
            chartDataXSD += "<A3>1.287</A3>";
            chartDataXSD += "<B3>0.03</B3>";
            chartDataXSD += "<B4>1.97</B4>";
            chartDataXSD += "<B5>0.029</B5>";
            chartDataXSD += "<B6>1.874</B6>";
            chartDataXSD += "<D1>0</D1>";
            chartDataXSD += "<D2>5.078</D2>";
            chartDataXSD += "<D3>0</D3>";
            chartDataXSD += "<D4>2.004</D4>";
            chartDataXSD += "<C4>0.9515</C4>";
            chartDataXSD += "<C4_1>1.051</C4_1>";
            chartDataXSD += "<L_D1>2.534</L_D1>";
            chartDataXSD += "<L_D1_1>0.3946</L_D1_1>";
            chartDataXSD += "</ChartParameter>";
            chartDataXSD += "<ChartParameter>";
            chartDataXSD += "<ID>6</ID>";
            chartDataXSD += "<NUM>7</NUM>";
            chartDataXSD += "<A>1.134</A>";
            chartDataXSD += "<A2>0.419</A2>";
            chartDataXSD += "<A3>1.182</A3>";
            chartDataXSD += "<B3>0.118</B3>";
            chartDataXSD += "<B4>1.882</B4>";
            chartDataXSD += "<B5>0.113</B5>";
            chartDataXSD += "<B6>1.806</B6>";
            chartDataXSD += "<D1>0.204</D1>";
            chartDataXSD += "<D2>5.204</D2>";
            chartDataXSD += "<D3>0.076</D3>";
            chartDataXSD += "<D4>1.924</D4>";
            chartDataXSD += "<C4>0.9594</C4>";
            chartDataXSD += "<C4_1>1.0423</C4_1>";
            chartDataXSD += "<L_D1>2.704</L_D1>";
            chartDataXSD += "<L_D1_1>0.3698</L_D1_1>";
            chartDataXSD += "</ChartParameter>";
            chartDataXSD += "<ChartParameter>";
            chartDataXSD += "<ID>7</ID>";
            chartDataXSD += "<NUM>8</NUM>";
            chartDataXSD += "<A>1.061</A>";
            chartDataXSD += "<A2>0.373</A2>";
            chartDataXSD += "<A3>1.099</A3>";
            chartDataXSD += "<B3>0.185</B3>";
            chartDataXSD += "<B4>1.815</B4>";
            chartDataXSD += "<B5>0.179</B5>";
            chartDataXSD += "<B6>1.751</B6>";
            chartDataXSD += "<D1>0.338</D1>";
            chartDataXSD += "<D2>5.306</D2>";
            chartDataXSD += "<D3>0.136</D3>";
            chartDataXSD += "<D4>1.864</D4>";
            chartDataXSD += "<C4>0.965</C4>";
            chartDataXSD += "<C4_1>1.0363</C4_1>";
            chartDataXSD += "<L_D1>2.847</L_D1>";
            chartDataXSD += "<L_D1_1>0.3512</L_D1_1>";
            chartDataXSD += "</ChartParameter>";
            chartDataXSD += "<ChartParameter>";
            chartDataXSD += "<ID>8</ID>";
            chartDataXSD += "<NUM>9</NUM>";
            chartDataXSD += "<A>1</A>";
            chartDataXSD += "<A2>0.337</A2>";
            chartDataXSD += "<A3>1.032</A3>";
            chartDataXSD += "<B3>0.239</B3>";
            chartDataXSD += "<B4>1.761</B4>";
            chartDataXSD += "<B5>0.232</B5>";
            chartDataXSD += "<B6>1.707</B6>";
            chartDataXSD += "<D1>0.547</D1>";
            chartDataXSD += "<D2>5.393</D2>";
            chartDataXSD += "<D3>0.184</D3>";
            chartDataXSD += "<D4>1.816</D4>";
            chartDataXSD += "<C4>0.9693</C4>";
            chartDataXSD += "<C4_1>1.0317</C4_1>";
            chartDataXSD += "<L_D1>2.97</L_D1>";
            chartDataXSD += "<L_D1_1>0.3367</L_D1_1>";
            chartDataXSD += "</ChartParameter>";
            chartDataXSD += "<ChartParameter>";
            chartDataXSD += "<ID>9</ID>";
            chartDataXSD += "<NUM>10</NUM>";
            chartDataXSD += "<A>0.949</A>";
            chartDataXSD += "<A2>0.308</A2>";
            chartDataXSD += "<A3>0.975</A3>";
            chartDataXSD += "<B3>0.284</B3>";
            chartDataXSD += "<B4>1.716</B4>";
            chartDataXSD += "<B5>2.276</B5>";
            chartDataXSD += "<B6>1.669</B6>";
            chartDataXSD += "<D1>0.687</D1>";
            chartDataXSD += "<D2>5.469</D2>";
            chartDataXSD += "<D3>0.223</D3>";
            chartDataXSD += "<D4>1.777</D4>";
            chartDataXSD += "<C4>0.9727</C4>";
            chartDataXSD += "<C4_1>1.0281</C4_1>";
            chartDataXSD += "<L_D1>3.078</L_D1>";
            chartDataXSD += "<L_D1_1>0.3249</L_D1_1>";
            chartDataXSD += "</ChartParameter>";
            chartDataXSD += "<ChartParameter>";
            chartDataXSD += "<ID>10</ID>";
            chartDataXSD += "<NUM>11</NUM>";
            chartDataXSD += "<A>0.905</A>";
            chartDataXSD += "<A2>0.285</A2>";
            chartDataXSD += "<A3>0.927</A3>";
            chartDataXSD += "<B3>0.321</B3>";
            chartDataXSD += "<B4>1.679</B4>";
            chartDataXSD += "<B5>0.313</B5>";
            chartDataXSD += "<B6>1.637</B6>";
            chartDataXSD += "<D1>0.811</D1>";
            chartDataXSD += "<D2>5.535</D2>";
            chartDataXSD += "<D3>0.256</D3>";
            chartDataXSD += "<D4>1.744</D4>";
            chartDataXSD += "<C4>0.9754</C4>";
            chartDataXSD += "<C4_1>1.0252</C4_1>";
            chartDataXSD += "<L_D1>3.173</L_D1>";
            chartDataXSD += "<L_D1_1>0.3152</L_D1_1>";
            chartDataXSD += "</ChartParameter>";
            chartDataXSD += "<ChartParameter>";
            chartDataXSD += "<ID>11</ID>";
            chartDataXSD += "<NUM>12</NUM>";
            chartDataXSD += "<A>0.866</A>";
            chartDataXSD += "<A2>0.266</A2>";
            chartDataXSD += "<A3>0.886</A3>";
            chartDataXSD += "<B3>0.354</B3>";
            chartDataXSD += "<B4>1.646</B4>";
            chartDataXSD += "<B5>0.346</B5>";
            chartDataXSD += "<B6>1.61</B6>";
            chartDataXSD += "<D1>0.922</D1>";
            chartDataXSD += "<D2>5.594</D2>";
            chartDataXSD += "<D3>0.283</D3>";
            chartDataXSD += "<D4>1.717</D4>";
            chartDataXSD += "<C4>0.9776</C4>";
            chartDataXSD += "<C4_1>1.0229</C4_1>";
            chartDataXSD += "<L_D1>3.258</L_D1>";
            chartDataXSD += "<L_D1_1>0.3069</L_D1_1>";
            chartDataXSD += "</ChartParameter>";
            chartDataXSD += "<ChartParameter>";
            chartDataXSD += "<ID>12</ID>";
            chartDataXSD += "<NUM>13</NUM>";
            chartDataXSD += "<A>0.832</A>";
            chartDataXSD += "<A2>0.249</A2>";
            chartDataXSD += "<A3>0.85</A3>";
            chartDataXSD += "<B3>0.382</B3>";
            chartDataXSD += "<B4>1.618</B4>";
            chartDataXSD += "<B5>0.374</B5>";
            chartDataXSD += "<B6>1.585</B6>";
            chartDataXSD += "<D1>1.025</D1>";
            chartDataXSD += "<D2>5.647</D2>";
            chartDataXSD += "<D3>0.307</D3>";
            chartDataXSD += "<D4>1.693</D4>";
            chartDataXSD += "<C4>0.9794</C4>";
            chartDataXSD += "<C4_1>1.021</C4_1>";
            chartDataXSD += "<L_D1>3.336</L_D1>";
            chartDataXSD += "<L_D1_1>0.2998</L_D1_1>";
            chartDataXSD += "</ChartParameter>";
            chartDataXSD += "<ChartParameter>";
            chartDataXSD += "<ID>13</ID>";
            chartDataXSD += "<NUM>14</NUM>";
            chartDataXSD += "<A>0.802</A>";
            chartDataXSD += "<A2>0.235</A2>";
            chartDataXSD += "<A3>0.817</A3>";
            chartDataXSD += "<B3>0.406</B3>";
            chartDataXSD += "<B4>1.594</B4>";
            chartDataXSD += "<B5>0.399</B5>";
            chartDataXSD += "<B6>1.563</B6>";
            chartDataXSD += "<D1>1.118</D1>";
            chartDataXSD += "<D2>5.696</D2>";
            chartDataXSD += "<D3>0.328</D3>";
            chartDataXSD += "<D4>1.672</D4>";
            chartDataXSD += "<C4>0.981</C4>";
            chartDataXSD += "<C4_1>1.0194</C4_1>";
            chartDataXSD += "<L_D1>3.407</L_D1>";
            chartDataXSD += "<L_D1_1>0.2935</L_D1_1>";
            chartDataXSD += "</ChartParameter>";
            chartDataXSD += "<ChartParameter>";
            chartDataXSD += "<ID>14</ID>";
            chartDataXSD += "<NUM>15</NUM>";
            chartDataXSD += "<A>0.775</A>";
            chartDataXSD += "<A2>0.223</A2>";
            chartDataXSD += "<A3>0.789</A3>";
            chartDataXSD += "<B3>0.428</B3>";
            chartDataXSD += "<B4>1.572</B4>";
            chartDataXSD += "<B5>0.421</B5>";
            chartDataXSD += "<B6>1.544</B6>";
            chartDataXSD += "<D1>1.203</D1>";
            chartDataXSD += "<D2>5.741</D2>";
            chartDataXSD += "<D3>0.347</D3>";
            chartDataXSD += "<D4>1.653</D4>";
            chartDataXSD += "<C4>0.9823</C4>";
            chartDataXSD += "<C4_1>1.018</C4_1>";
            chartDataXSD += "<L_D1>3.472</L_D1>";
            chartDataXSD += "<L_D1_1>0.288</L_D1_1>";
            chartDataXSD += "</ChartParameter>";
            chartDataXSD += "<ChartParameter>";
            chartDataXSD += "<ID>15</ID>";
            chartDataXSD += "<NUM>16</NUM>";
            chartDataXSD += "<A>0.75</A>";
            chartDataXSD += "<A2>0.212</A2>";
            chartDataXSD += "<A3>0.763</A3>";
            chartDataXSD += "<B3>0.448</B3>";
            chartDataXSD += "<B4>1.552</B4>";
            chartDataXSD += "<B5>0.44</B5>";
            chartDataXSD += "<B6>1.526</B6>";
            chartDataXSD += "<D1>1.282</D1>";
            chartDataXSD += "<D2>5.782</D2>";
            chartDataXSD += "<D3>0.363</D3>";
            chartDataXSD += "<D4>1.637</D4>";
            chartDataXSD += "<C4>0.9835</C4>";
            chartDataXSD += "<C4_1>1.0168</C4_1>";
            chartDataXSD += "<L_D1>3.532</L_D1>";
            chartDataXSD += "<L_D1_1>0.2831</L_D1_1>";
            chartDataXSD += "</ChartParameter>";
            chartDataXSD += "<ChartParameter>";
            chartDataXSD += "<ID>16</ID>";
            chartDataXSD += "<NUM>17</NUM>";
            chartDataXSD += "<A>0.728</A>";
            chartDataXSD += "<A2>0.203</A2>";
            chartDataXSD += "<A3>0.739</A3>";
            chartDataXSD += "<B3>0.466</B3>";
            chartDataXSD += "<B4>1.534</B4>";
            chartDataXSD += "<B5>0.458</B5>";
            chartDataXSD += "<B6>1.511</B6>";
            chartDataXSD += "<D1>1.356</D1>";
            chartDataXSD += "<D2>5.82</D2>";
            chartDataXSD += "<D3>0.378</D3>";
            chartDataXSD += "<D4>1.622</D4>";
            chartDataXSD += "<C4>0.9845</C4>";
            chartDataXSD += "<C4_1>1.0157</C4_1>";
            chartDataXSD += "<L_D1>3.588</L_D1>";
            chartDataXSD += "<L_D1_1>0.2787</L_D1_1>";
            chartDataXSD += "</ChartParameter>";
            chartDataXSD += "<ChartParameter>";
            chartDataXSD += "<ID>17</ID>";
            chartDataXSD += "<NUM>18</NUM>";
            chartDataXSD += "<A>0.707</A>";
            chartDataXSD += "<A2>0.194</A2>";
            chartDataXSD += "<A3>0.718</A3>";
            chartDataXSD += "<B3>0.482</B3>";
            chartDataXSD += "<B4>1.518</B4>";
            chartDataXSD += "<B5>0.475</B5>";
            chartDataXSD += "<B6>1.496</B6>";
            chartDataXSD += "<D1>1.424</D1>";
            chartDataXSD += "<D2>5.856</D2>";
            chartDataXSD += "<D3>0.391</D3>";
            chartDataXSD += "<D4>1.608</D4>";
            chartDataXSD += "<C4>0.9854</C4>";
            chartDataXSD += "<C4_1>1.0148</C4_1>";
            chartDataXSD += "<L_D1>3.64</L_D1>";
            chartDataXSD += "<L_D1_1>0.2747</L_D1_1>";
            chartDataXSD += "</ChartParameter>";
            chartDataXSD += "<ChartParameter>";
            chartDataXSD += "<ID>18</ID>";
            chartDataXSD += "<NUM>19</NUM>";
            chartDataXSD += "<A>0.688</A>";
            chartDataXSD += "<A2>0.187</A2>";
            chartDataXSD += "<A3>0.698</A3>";
            chartDataXSD += "<B3>0.497</B3>";
            chartDataXSD += "<B4>1.503</B4>";
            chartDataXSD += "<B5>0.49</B5>";
            chartDataXSD += "<B6>1.483</B6>";
            chartDataXSD += "<D1>1.487</D1>";
            chartDataXSD += "<D2>5.891</D2>";
            chartDataXSD += "<D3>0.403</D3>";
            chartDataXSD += "<D4>1.597</D4>";
            chartDataXSD += "<C4>0.9862</C4>";
            chartDataXSD += "<C4_1>1.014</C4_1>";
            chartDataXSD += "<L_D1>3.689</L_D1>";
            chartDataXSD += "<L_D1_1>0.2711</L_D1_1>";
            chartDataXSD += "</ChartParameter>";
            chartDataXSD += "<ChartParameter>";
            chartDataXSD += "<ID>19</ID>";
            chartDataXSD += "<NUM>20</NUM>";
            chartDataXSD += "<A>0.671</A>";
            chartDataXSD += "<A2>0.18</A2>";
            chartDataXSD += "<A3>0.68</A3>";
            chartDataXSD += "<B3>0.51</B3>";
            chartDataXSD += "<B4>1.49</B4>";
            chartDataXSD += "<B5>0.504</B5>";
            chartDataXSD += "<B6>1.47</B6>";
            chartDataXSD += "<D1>1.549</D1>";
            chartDataXSD += "<D2>5.921</D2>";
            chartDataXSD += "<D3>0.415</D3>";
            chartDataXSD += "<D4>1.585</D4>";
            chartDataXSD += "<C4>0.9869</C4>";
            chartDataXSD += "<C4_1>1.0133</C4_1>";
            chartDataXSD += "<L_D1>3.735</L_D1>";
            chartDataXSD += "<L_D1_1>0.2677</L_D1_1>";
            chartDataXSD += "</ChartParameter>";
            chartDataXSD += "<ChartParameter>";
            chartDataXSD += "<ID>20</ID>";
            chartDataXSD += "<NUM>21</NUM>";
            chartDataXSD += "<A>0.655</A>";
            chartDataXSD += "<A2>0.173</A2>";
            chartDataXSD += "<A3>0.663</A3>";
            chartDataXSD += "<B3>0.523</B3>";
            chartDataXSD += "<B4>1.477</B4>";
            chartDataXSD += "<B5>0.516</B5>";
            chartDataXSD += "<B6>1.459</B6>";
            chartDataXSD += "<D1>1.605</D1>";
            chartDataXSD += "<D2>5.951</D2>";
            chartDataXSD += "<D3>0.425</D3>";
            chartDataXSD += "<D4>1.575</D4>";
            chartDataXSD += "<C4>0.9876</C4>";
            chartDataXSD += "<C4_1>1.0126</C4_1>";
            chartDataXSD += "<L_D1>3.778</L_D1>";
            chartDataXSD += "<L_D1_1>0.2647</L_D1_1>";
            chartDataXSD += "</ChartParameter>";
            chartDataXSD += "<ChartParameter>";
            chartDataXSD += "<ID>21</ID>";
            chartDataXSD += "<NUM>22</NUM>";
            chartDataXSD += "<A>0.64</A>";
            chartDataXSD += "<A2>0.167</A2>";
            chartDataXSD += "<A3>0.647</A3>";
            chartDataXSD += "<B3>0.534</B3>";
            chartDataXSD += "<B4>1.466</B4>";
            chartDataXSD += "<B5>0.528</B5>";
            chartDataXSD += "<B6>1.448</B6>";
            chartDataXSD += "<D1>1.659</D1>";
            chartDataXSD += "<D2>5.979</D2>";
            chartDataXSD += "<D3>0.434</D3>";
            chartDataXSD += "<D4>1.566</D4>";
            chartDataXSD += "<C4>0.9882</C4>";
            chartDataXSD += "<C4_1>1.0119</C4_1>";
            chartDataXSD += "<L_D1>3.819</L_D1>";
            chartDataXSD += "<L_D1_1>0.2618</L_D1_1>";
            chartDataXSD += "</ChartParameter>";
            chartDataXSD += "<ChartParameter>";
            chartDataXSD += "<ID>22</ID>";
            chartDataXSD += "<NUM>23</NUM>";
            chartDataXSD += "<A>0.626</A>";
            chartDataXSD += "<A2>0.162</A2>";
            chartDataXSD += "<A3>0.633</A3>";
            chartDataXSD += "<B3>0.545</B3>";
            chartDataXSD += "<B4>1.455</B4>";
            chartDataXSD += "<B5>0.539</B5>";
            chartDataXSD += "<B6>1.438</B6>";
            chartDataXSD += "<D1>1.71</D1>";
            chartDataXSD += "<D2>6.006</D2>";
            chartDataXSD += "<D3>0.443</D3>";
            chartDataXSD += "<D4>1.557</D4>";
            chartDataXSD += "<C4>0.9887</C4>";
            chartDataXSD += "<C4_1>1.0114</C4_1>";
            chartDataXSD += "<L_D1>3.858</L_D1>";
            chartDataXSD += "<L_D1_1>0.2592</L_D1_1>";
            chartDataXSD += "</ChartParameter>";
            chartDataXSD += "<ChartParameter>";
            chartDataXSD += "<ID>23</ID>";
            chartDataXSD += "<NUM>24</NUM>";
            chartDataXSD += "<A>0.612</A>";
            chartDataXSD += "<A2>0.157</A2>";
            chartDataXSD += "<A3>0.619</A3>";
            chartDataXSD += "<B3>0.555</B3>";
            chartDataXSD += "<B4>1.445</B4>";
            chartDataXSD += "<B5>0.549</B5>";
            chartDataXSD += "<B6>1.429</B6>";
            chartDataXSD += "<D1>1.759</D1>";
            chartDataXSD += "<D2>6.031</D2>";
            chartDataXSD += "<D3>0.451</D3>";
            chartDataXSD += "<D4>1.548</D4>";
            chartDataXSD += "<C4>0.9892</C4>";
            chartDataXSD += "<C4_1>1.0109</C4_1>";
            chartDataXSD += "<L_D1>3.895</L_D1>";
            chartDataXSD += "<L_D1_1>0.2567</L_D1_1>";
            chartDataXSD += "</ChartParameter>";
            chartDataXSD += "<ChartParameter>";
            chartDataXSD += "<ID>24</ID>";
            chartDataXSD += "<NUM>25</NUM>";
            chartDataXSD += "<A>0.6</A>";
            chartDataXSD += "<A2>0.153</A2>";
            chartDataXSD += "<A3>0.606</A3>";
            chartDataXSD += "<B3>0.565</B3>";
            chartDataXSD += "<B4>1.435</B4>";
            chartDataXSD += "<B5>0.559</B5>";
            chartDataXSD += "<B6>1.42</B6>";
            chartDataXSD += "<D1>1.806</D1>";
            chartDataXSD += "<D2>6.056</D2>";
            chartDataXSD += "<D3>0.459</D3>";
            chartDataXSD += "<D4>1.541</D4>";
            chartDataXSD += "<C4>0.9896</C4>";
            chartDataXSD += "<C4_1>1.0105</C4_1>";
            chartDataXSD += "<L_D1>3.931</L_D1>";
            chartDataXSD += "<L_D1_1>0.2544</L_D1_1>";
            chartDataXSD += "</ChartParameter>";
            chartDataXSD += "</NewDataSet>";

            stream = new StringReader(chartDataXSD);

            return stream;
        }
    }
}