<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
		<TargetFramework>net5</TargetFramework>
		<IsPackable>true</IsPackable>
		<Version>1.0.2-rc1</Version>
		<Description>
			用户中心
		</Description>
		<PackageReleaseNotes>
			+优化 返回用户DTO新增FullName---2022/3/15
			+修复 权限验证-菜单标识验重问题---2022/5/2
			+优化 权限规则-新增字段IframeUrl内嵌第三方地址(报表平台)---2022/5/11
		</PackageReleaseNotes>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <DocumentationFile>bin\Debug\UserCenter.xml</DocumentationFile>
        <OutputPath>bin\Debug\</OutputPath>
        <NoWarn>1701;1702;1591</NoWarn>
        <WarningLevel>5</WarningLevel>
    </PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DocumentationFile>bin\Debug\netcoreapp3.1\UserCenter.xml</DocumentationFile>
		<OutputPath>bin\Debug\netcoreapp3.1\</OutputPath>
	</PropertyGroup>

    <ItemGroup>
		<PackageReference Include="Ardalis.SmartEnum" Version="2.1.0" />
      <ProjectReference Include="..\..\MF\MF.Cache\MF.Cache.csproj" />
      <ProjectReference Include="..\..\MF\MF.Mapster\MF.Mapster.csproj" />
      <ProjectReference Include="..\..\MF\MF.Masuit\MF.Masuit.csproj" />
      <ProjectReference Include="..\..\MF\SimplCommerce.Modules\SimplCommerce.Modules.csproj" />
      <ProjectReference Include="..\MF.Modules.User.Shared\MF.Modules.UserCenter.Shared.csproj" />
    </ItemGroup>
</Project>