<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>netcoreapp3.1;net5</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="4.7.10" />
    <PackageReference Include="Quartz" Version="3.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MF.Rest\MF.Rest.csproj" />
  </ItemGroup>

</Project>
