<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net5.0</TargetFramework>
		<Version>1.0.3-rc9.6</Version>
		<Description>缓存工具</Description>
		<PackageReleaseNotes>
			升级ORM:SqlSugarCore
		</PackageReleaseNotes>
		<AssemblyName>MF.Cache</AssemblyName>
		<RootNamespace>MF.Cache</RootNamespace>
		<AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
		<RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
	</PropertyGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="AspectInjector" Version="2.7.3-pre1" />
		<PackageReference Include="CSRedisCore" Version="3.6.6" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\MF.Orm\MF.Orm.csproj" />
	</ItemGroup>
</Project>